### ISSUE TITLE
Web interface refuses scrolling

### ISSUE THREAD

**Issue by FooBarWidget** [CenturyLinkLabs/imagelayers-graph#78]
Reproduction steps:

1. Visit https://imagelayers.io/?images=phusion%2Fbaseimage:latest with a browser window size that is small enough such that the page does not fit in the window, and requires a scrollbar.
2. Scroll down.

Expected results:
Scrolling works normally.

Actual results:
The page "jumps back", refusing to scroll down.

I am on Chrome 43, OS X.

**Comment by rheinwein** [comment]
Thanks @FooBarWidget!

Looks like this is a weird case where the image layer graph is roughly the same size as the viewport. I'll start working on a fix.

**Comment by rheinwein** [comment]
Hey @FooBarWidget -- give it a try now.

**Comment by FooBarWidget** [comment]
Yes it's been fixed.
