### ISSUE TITLE
Support registries other than docker hub

### ISSUE THREAD

**Issue by F21** [CenturyLinkLabs/imagelayers-graph#80]
Would love to see support for registries such as quay.io and gcr.io

**Comment by jumanjiman** [comment]
yes, support for other registries would be useful

**Comment by argvader** [comment]
Thanks for the feedback but we don't have any plans to add additional repository support into imagelayers at the moment. The codebase for the repository data is in the [imagelayers](https://github.com/CenturyLinkLabs/imagelayers) project if you have the desire to add it yourself. I should have responded sooner. Sorry to leave everyone hanging.
